import "~/app/_styles/globals.css";
import localFont from "next/font/local";
import { Metadata } from "next";
import Body from "~/app/_components/Body";
import { ReactNode } from "react";

/**
 * Application root metadata
 */
export const metadata: Metadata = {
  title: "beatattoos",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  appleWebApp: { statusBarStyle: "black-translucent", capable: true },
};

/**
 * Import Proclamate Heavy local font
 */
const proclamateHeavy = localFont({
  src: [{ path: "../../public/fonts/proclamate_heavy.woff" }],
  variable: "--font-proclamate-heavy",
});

/**
 * Props for {@link RootLayout}
 */
interface RootLayoutProps {
  children: ReactNode;
}

/**
 * Layout for application root
 */
export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="en" className={`${proclamateHeavy.variable}`}>
      <Body>{props.children}</Body>
    </html>
  );
}
