// Styles
import "~/app/_styles/globals.css";

// Helpers
import localFont from "@next/font/local";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  appleWebApp: { statusBarStyle: "black-translucent", capable: true },
};

const proclamateHeavy = localFont({
  src: [{ path: "../../public/fonts/proclamate_heavy.woff" }],
  variable: "--font-proclamate-heavy",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${proclamateHeavy.variable}`}>
      <body className={"bg-secondary-600"}>{children}</body>
    </html>
  );
}
