/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 man.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/man.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.man.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, 0]} scale={0.23} />
    </group>
  )
}

useGLTF.preload('/man.gltf')
