/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 untitled1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['BaseMesh_Low_Res-Detailed_Male-Femalelwo'].geometry} material={materials.Default} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/untitled1.gltf')
