import "~/app/_styles/globals.css";

import localFont from "next/font/local";
import { ReactNode } from "react";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

/**
 * Import Proclamate Heavy local font
 */
const proclamateHeavy = localFont({
  src: [{ path: "../../public/fonts/proclamate_heavy.woff" }],
  variable: "--font-proclamate-heavy",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${proclamateHeavy.variable}`}>
      <body>{children}</body>
    </html>
  );
}
