name: Run tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - "src/apps/**"
      - "src/packages/**"
  push:
    branches:
      - main
    paths:
      - "src/apps/**"
      - "src/packages/**"

jobs:
  test-admin:
    name: Run admin app tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/apps/admin
    env:
      NEXTAUTH_SECRET: ${{ vars.ADMIN_NEXTAUTH_SECRET }}
      NEXTAUTH_URL: ${{ vars.ADMIN_NEXTAUTH_URL }}
      NEXT_PUBLIC_CI: "1"
      DISCORD_CLIENT_ID: ${{ vars.ADMIN_DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ vars.ADMIN_DISCORD_CLIENT_SECRET }}
      ADMIN_TOKEN: ${{ vars.ADMIN_TOKEN }}
      DATABASE_URL: ${{ vars.ADMIN_DATABASE_URL }}
      DIRECT_URL: ${{ vars.ADMIN_DIRECT_URL }}
    steps:
      - name: Checkout beatattoos repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install monorepo dependencies
        working-directory: ./src
        run: npm ci
      - name: Setup supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Initialize supabase database
        run: supabase init --with-intellij-settings --with-vscode-settings
      - name: Start supabase database
        run: supabase db start
      - name: Reset supabase database
        run: supabase db reset
      - name: Install db package dependencies
        working-directory: ./src/packages/db
        run: npm ci
      - name: Generate prisma client
        working-directory: ./src/packages/db
        run: npm run postinstall
      - name: Push tables to database
        working-directory: ./src/packages/db
        run: npm run db:push
      - name: Import geonames into database
        working-directory: ./src/packages/db
        run: npm run import-geonames
      - name: Import alternate names into database
        working-directory: ./src/packages/db
        run: npm run import-alternatenames
      - name: Install admin app dependencies
        run: npm ci
      - name: Build admin app
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Install playwright
        run: npx playwright install --with-deps
      - name: Run playwright e2e tests
        run: npm run test-e2e
      - name: Run unit and integration vitest tests
        run: npm run test